jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release pipeline
        run: npx semantic-release
name: Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
